version: '3.7'

services:
  database_crud:
    image: postgres
    container_name: crud_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=crud
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: crud_node
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local
